databases:
  - name: shapeteam-db
    plan: free
    databaseName: shapeteamdb
    user: lbdev

services:
  - type: web
    plan: free
    name: ShapeteamAPI
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shapeteam-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
