# Generated by Django 5.0.2 on 2025-02-01 15:33

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(default='profile.png', upload_to=apps.user.models.upload_thumbnail),
        ),
    ]
