# Generated by Django 5.0.2 on 2025-02-18 06:07

import apps.user.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(blank=True, choices=[(1, 'Hipertrofia Muscular '), (2, 'Perda de Peso '), (3, 'Definição Muscular '), (4, 'Ganho de Resistência'), (5, 'Aumento de Força '), (6, 'Saúde e Bem-estar '), (7, 'Melhora da Mobilidade e Flexibilidade '), (8, 'Reabilitação Física '), (9, 'Condicionamento Esportivo')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(default='profile.png', max_length=255, validators=[apps.user.models.file_validation]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goal',
            field=models.ManyToManyField(to='user.goal'),
        ),
    ]
