# Generated by Django 5.0.2 on 2024-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeteam', '0002_rename_message_chat_alter_nameexercise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
