# Generated by Django 5.0.2 on 2024-11-09 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shapeteam', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daytraining',
            name='exercises',
            field=models.ManyToManyField(to='shapeteam.exercise'),
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapeteam.exercise'),
        ),
        migrations.AddField(
            model_name='exerciseranking',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapeteam.exercise'),
        ),
        migrations.AddField(
            model_name='exerciseranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_exe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='shapeteam.nameexercise'),
        ),
        migrations.CreateModel(
            name='WeekRoutine',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('friday', models.ManyToManyField(blank=True, related_name='friday_routine', to='shapeteam.daytraining')),
                ('monday', models.ManyToManyField(blank=True, related_name='monday_routine', to='shapeteam.daytraining')),
                ('saturday', models.ManyToManyField(blank=True, related_name='saturday_routine', to='shapeteam.daytraining')),
                ('sunday', models.ManyToManyField(blank=True, related_name='sunday_routine', to='shapeteam.daytraining')),
                ('thursday', models.ManyToManyField(blank=True, related_name='thursday_routine', to='shapeteam.daytraining')),
                ('tuesday', models.ManyToManyField(blank=True, related_name='tuesday_routine', to='shapeteam.daytraining')),
                ('wednesday', models.ManyToManyField(blank=True, related_name='wednesday_routine', to='shapeteam.daytraining')),
            ],
            options={
                'verbose_name': 'Week Routine',
                'verbose_name_plural': 'Week Routines',
            },
        ),
        migrations.AddField(
            model_name='daytraining',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapeteam.weekroutine'),
        ),
    ]
