# Generated by Django 5.0.2 on 2024-12-17 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shapeteam', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daytraining',
            name='exercises',
            field=models.ManyToManyField(to='shapeteam.exercise'),
        ),
        migrations.AddField(
            model_name='exerciseranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gym',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
        migrations.AddField(
            model_name='exerciseranking',
            name='muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapeteam.musclegroup'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shapeteam.musclegroup'),
        ),
        migrations.CreateModel(
            name='WeekRoutine',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('days_training', models.ManyToManyField(to='shapeteam.daytraining', verbose_name='Days training')),
            ],
            options={
                'verbose_name': 'Week Routine',
                'verbose_name_plural': 'Week Routines',
            },
        ),
        migrations.AddField(
            model_name='daytraining',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapeteam.weekroutine'),
        ),
    ]
