# Generated by Django 5.0.2 on 2025-02-06 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shapeteam', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseranking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gym',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapeteam.musclegroup'),
        ),
        migrations.AddField(
            model_name='daytraining',
            name='muscle_group',
            field=models.ManyToManyField(to='shapeteam.musclegroup'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shapeteam.musclegroup'),
        ),
        migrations.AddField(
            model_name='userperformancemetrics',
            name='muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shapeteam.musclegroup'),
        ),
        migrations.AddField(
            model_name='userperformancemetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekroutine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daytraining',
            name='week_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shapeteam.weekroutine'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', 'type', 'muscle_group'], name='shapeteam_a_user_id_246311_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['achieved_at'], name='shapeteam_a_achieve_162833_idx'),
        ),
        migrations.AddIndex(
            model_name='userperformancemetrics',
            index=models.Index(fields=['user', 'muscle_group'], name='shapeteam_u_user_id_894f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='userperformancemetrics',
            index=models.Index(fields=['updated_at'], name='shapeteam_u_updated_2edd8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userperformancemetrics',
            unique_together={('user', 'muscle_group')},
        ),
    ]
