# Generated by Django 5.0.2 on 2025-01-19 16:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytraining',
            name='week_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shapeteam.weekroutine'),
        ),
        migrations.AlterField(
            model_name='weekroutine',
            name='created_at',
            field=models.DateField(db_default=datetime.date(2025, 1, 19)),
        ),
    ]
