# Generated by Django 5.0.2 on 2025-02-16 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeteam', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekroutine',
            name='created_at',
            field=models.DateField(db_default=datetime.date(2025, 2, 16)),
        ),
    ]
