# Generated by Django 5.0.2 on 2025-02-02 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeteam', '0002_alter_daytraining_week_routine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekroutine',
            name='created_at',
            field=models.DateField(db_default=datetime.date(2025, 2, 2)),
        ),
    ]
