# Generated by Django 5.0.2 on 2025-02-18 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeteam', '0003_alter_weekroutine_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekroutine',
            name='created_at',
            field=models.DateField(db_default=datetime.date(2025, 2, 18)),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
