# Generated by Django 5.1.7 on 2025-04-17 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapeteam', '0004_alter_weekroutine_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekroutine',
            name='created_at',
            field=models.DateField(db_default=datetime.date(2025, 4, 17)),
        ),
    ]
