# Generated by Django 5.0.2 on 2024-11-09 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('shapeteam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shapeteam.connection'),
        ),
    ]
